# Generated by Django 3.2.7 on 2021-10-04 01:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0010_alter_tipo_telefono_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('codAlergia', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Alergia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Alergia')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergia',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('codEnfermedad', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Enfermedad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Enfermedad')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('codMedicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Medicacion')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Medicacion')),
            ],
            options={
                'verbose_name': 'Medicacion',
                'verbose_name_plural': 'Medicacion',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('codSintoma', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Sintoma')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Sintoma')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre Sintoma')),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintoma',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('codHistoriaClinica', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de H.C.')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('alergia', models.ManyToManyField(blank=True, to='Atencion.Alergia')),
                ('enfermedades', models.ManyToManyField(blank=True, to='Atencion.Enfermedad')),
                ('medicacion', models.ManyToManyField(blank=True, to='Atencion.Medicacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.paciente')),
            ],
            options={
                'verbose_name': 'HistoriaClinica',
                'verbose_name_plural': 'HistoriaClinica',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('codAtencion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Atencion')),
                ('fechaIngreso', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Ingreso')),
                ('motivoAtencion', models.CharField(max_length=120, verbose_name='Motivo de la atencion')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tensionArterial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('frecuenciaCardiaca', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saturacionOxigeno', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.enfermero')),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atencion.historiaclinica')),
                ('medicacion', models.ManyToManyField(blank=True, to='Atencion.Medicacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.medico')),
                ('sintomas', models.ManyToManyField(blank=True, to='Atencion.Sintoma')),
            ],
        ),
    ]
