# Generated by Django 3.2.7 on 2021-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='codUnidadMedida',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Medida'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Unidad Medida'),
        ),
    ]
