# Generated by Django 3.2.7 on 2021-10-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atencion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='fechaIngreso',
            new_name='date_joined',
        ),
    ]
