# Generated by Django 3.2.7 on 2021-10-01 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='horaInicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
