# Generated by Django 3.2.7 on 2021-10-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_alter_tipo_telefono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
