# Generated by Django 3.2.7 on 2021-10-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_alter_tipo_telefono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
